### ISSUE TITLE
[BE/채팅] 

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#110]
- [x] 단체 채팅에서 멤버를 보내줄 때, 아이디와 닉네임까지 보내야함 -> [{id: string, name: string}...]
- [x] 몽고 디비에 생성한 채팅방이 저장이 안됨
- [x] 모든 room-view의 처음 log는 {sender: null, message: "user1, user2님이 참가하셨습니다"}
- [x] leave-room했을 때 send-message에서 오는 퇴장 메세지 DB에 저장하기

**Comment by abc7468** [comment]
이슈 모두 해결하였습니다! 확인해보시고 안되는거 있으시면 다시 말씀해주세요!

**Comment by minjyo** [comment]
개인 채팅방 생성 시 private: false 로 오는 오류 해결 부탁드립니다.

**Comment by minjyo** [comment]
입장 메세지
front1 front2 님이 대화에 참여하셨습니다.
-> front1, front2 님이 대화에 참여하셨습니다. 
로 변경 가능할까요?

**Comment by abc7468** [comment]
@minjyo 
두 부분 모두 수정하고 말씀드리겠습니다.

**Comment by minjyo** [comment]
![스크린샷 2022-02-19 오후 4 40 53](https://user-images.githubusercontent.com/24283401/154791806-a957c86e-8119-4516-a307-94d1605a57a6.png)

유저가 방을 떠나도 room-view시, 멤버가 그대로 있는 오류 수정 부탁드립니다.

**Comment by abc7468** [comment]
모두 수정 완료하였습니다. 확인하시면 이슈 클로즈 부탁드릴게요~

**Comment by minjyo** [comment]
확인했습니다.
