### ISSUE TITLE
[BE/리뷰] 리뷰 등록

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#115]
header
![스크린샷 2022-02-19 오후 10 28 55](https://user-images.githubusercontent.com/24283401/154802819-b11526a3-2f8e-4487-bdfc-2049320bec6f.png)

request 
![스크린샷 2022-02-19 오후 10 29 13](https://user-images.githubusercontent.com/24283401/154802831-078b1444-dc1a-4958-8823-224f9a7fafd7.png)

response
![스크린샷 2022-02-19 오후 10 29 29](https://user-images.githubusercontent.com/24283401/154802842-8fe91df9-2f7a-4294-9a18-967e1ab59686.png)

**Comment by abc7468** [comment]
api 문서 상 req값을 bool로 뒀으나 db에서 int로 처리하여 캐스팅 미스로 일어난 에러.
프론트 쪽에서 false 를 0, true 를 1로 처리하면서 해결.
