### ISSUE TITLE
[FE/상점] get cors error

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#21]
![8159c233e7ee69649e2b8e0da724bbc20c68e61ecfc3b942b46fccfb956e0fad](https://user-images.githubusercontent.com/48500209/150895273-156c0cac-faf4-4f71-b96a-172256645712.png)

**Comment by abc7468** [comment]
[grpc gateway cors 해결](https://github.com/STOVE-Milk/steam-clone/issues/22)
cors 허용 헤더를 추가함으로써 이슈 해결하였습니다.
