### ISSUE TITLE
[FE / nextjs] 렌더링하면 데이터가 undefined 로 뜨는 문제

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#27]
**CASE # 1**
`<Text types="medium">{gameData.name}</Text>` 나  `{Boolean(gameData.sale) && <SaleBadge>-{gameData.sale}%</SaleBadge>}` 처럼 데이터를 불러오기만 하는 부분은 문제없이 잘 나온다.
![image](https://user-images.githubusercontent.com/48500209/151123381-bf14f37d-098e-4b26-ab81-cb5443c9f252.png)

**CASE # 2**
`            
{Boolean(gameData.sale) ? (
              <>
                {/* 로그인할 때, 유저 돈 단위 정보도 가져오기*/}
                <DefaultPrice>{`${localePrice(gameData.price, 'KR')}`}</DefaultPrice>
                <Text types="medium">{`${localePrice((gameData.price / 100) * (100 - gameData.sale), 'KR')}`}</Text>
              </>
            ) : (
              <Text types="medium">{`${localePrice(gameData.price, 'KR')}`}</Text>
            )}
`
이 경우처럼 `localePrice`과 같은 util 함수나
`            {gameData.os_list.map((eachOs: string) => {
              return <FontAwesomeIcon icon={eachOs === 'windows' ? faWindowMaximize : faAppleAlt} inverse />;
            })}`
map과 같은 특정함수를 쓰려고 하면 undefined이슈가 발생한다.

![image](https://user-images.githubusercontent.com/48500209/151123812-555a5828-b3eb-4015-8d42-e19871342d66.png)

**CASE # 3**
새로고침 전 프리렌더링전에는 util함수가 쓰이는 price 부분 데이터를 잘 불러온다
![image](https://user-images.githubusercontent.com/48500209/151123500-8217b8b4-86a3-4878-b4ca-2f8e7a0adefb.png)

새로고침 후에는 
![image](https://user-images.githubusercontent.com/48500209/151123264-4f9dfae0-0a53-4652-a18a-e4027dd44a66.png)

**Comment by minjyo** [comment]
### 해결방법
module/game/reducer.tsx 에서 load안의 파라미터를 다음과 같이 고친다.
<img width="324" alt="스크린샷 2022-01-26 오후 6 28 06" src="https://user-images.githubusercontent.com/24283401/151137553-1664afae-1afc-49a1-b908-b74de42906c8.png">

### 문제가 발생한 이유
컴포넌트에서 useSelector로 스토어의 값(game, categories)을 가져와 뷰에서 map을 사용해 뿌려주기 떄문에, 해당 값이 null이거나 undefined면 오류가 발생한다.
액션의 호출 흐름은 initail() -> load() -> success() / failure()으로 이루어지고 각 함수들의 파라미터는 action.payload이다. 그런데 이전에 load(action.payload)라는 코드는 내가 서버에 보내고자하는 파라미터(categories의 경우 없음, game의 경우 {id})를 스토어의 값(game, categories)에 넣기 때문에 오류가 발생하는 것이다. categories={}, game={id: 1}로 저장이 되어있는데 이 값들을 가지고 map을 하려고 시도하기 때문에 null이 아닌 undefined 오류가 발생하는 것을 알 수 있다.
따라서, 이를 방지하기 위해 load의 파라미터를 initialData를 넣어주어 해결할 수 있다.
