### ISSUE TITLE
[BE/ 빌드파일] jar 파일 실행이 되었다가 꺼져버립니다.

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#31]
**현 자바 버전**
![image](https://user-images.githubusercontent.com/48500209/151174659-5406dfcd-1505-44d4-bbd3-fac81ffbc1d6.png)

**에러**
![image](https://user-images.githubusercontent.com/48500209/151174692-d3c62fe9-1719-43dc-af1e-5e63de268d40.png)

**warning**
![image](https://user-images.githubusercontent.com/48500209/151174788-d9a4650c-5c74-4307-8e3b-79682af269cf.png)

**failed**
![image](https://user-images.githubusercontent.com/48500209/151174833-5df41c94-9b7c-4162-8571-74543cd2bed0.png)

**Comment by Tae-Hyeon** [comment]
1순위 vpn이 켜져 있어서 방화벽에 막히거나, 어떠한 이유로 인해 막힘
2순위 서버 방화벽에서 막힘
3순위 서버 다운으로 인해 연결 불가
4순위 jdk 버전 오류 (open jdk 11 - amazon correto)
