### ISSUE TITLE
[FE / axios] axios CORS 에러 w/ bearer token

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#34]
**Authorization이 필요한 API에 요청을 할 때 겪은 문제: bearer 토큰을 넣고 axios통신을 하려고하는데 cors에러가 나는 상황**
: 카테고리 리스트를 불러오는 get요청에서 CORS에러가 났고, 이부분에 대한 데이터를 불러오지 못하는 모습
(CORS 에서 에러가 나니가 요청도 안들어간듯함, 그 이유는 inital 로 설정했던 mockdata도 로딩을 못해왔기 때문)

![image](https://user-images.githubusercontent.com/48500209/151278597-9b4630c5-a726-4608-aa18-a8f4c4d782fa.png)

**시도했던 방법**

1. axios객체의 header에 Authorization을 넣어주는 방법
1-1  api 코드를 작성할 때, 직접 넣기
![image](https://user-images.githubusercontent.com/48500209/151278780-35a62e7e-78ea-4d29-8203-76014d684be1.png)

1-2 axios(사실상 1-1과 동일한 방법)
![image](https://user-images.githubusercontent.com/48500209/151278933-afa2e12b-0b8e-4f56-86d4-328e8e8d7f35.png)

=> 둘다 네트워크 탭에서 Header를 확인해보면 bearer토큰은 잘 들어가있는데, CORS에러뜸, 
그냥 header없이 순수 axios객체로만 통신하는 경우에는 잘 됨 (맨 첫 이미지 하단 카테고리별 게임정보 부분에 해당)

#22 #21 이 부분과 연관이 있나 싶긴한데,,,, 아직 연구중입니다.

**Comment by abc7468** [comment]
게이트웨이쪽에서 Authorization 헤더를 허락한 상태가 아니여서 생긴 문제입니다.
#21 에 기록해 둔 코드에서
[]string{"Content-Type", "Accept"} --> []string{"Content-Type", "Accept", "Authorization"}
변경하여 문제를 해결하였습니다.

**Comment by ummaeha** [comment]
충전관련 통신에서 CORS에러 동일하게 발생해서 이슈 reopen 합니다.

관련 이미지
- option
![image](https://user-images.githubusercontent.com/48500209/151300360-e151bd0c-51e7-4086-8eb4-50f1ea7d3675.png)

- get
![image](https://user-images.githubusercontent.com/48500209/151300406-e83da501-5540-4afa-ae6c-3c9a93af3a22.png)

**Comment by ummaeha** [comment]
일단 토큰 인증하는 부분 코드 없애고 `jar`파일 전달해주셔서 일단 개발 진행하고있습니다.

**Comment by Tae-Hyeon** [comment]
CORS 처리하기 전 JwtFilter를 거치면서 문제 발생
Authorization이 없는 OPTIONS 요청으로 CORS에 대한 정보를 불러올 때, JwtFilter에 걸리면서 Authorization을 null로 받게 되어 문제 --> JwtFilter에서 OPTIONS 필터링으로 해결
``` java
@Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain chain) throws IOException, ServletException {
        HttpServletRequest request = (HttpServletRequest) servletRequest;
        
        if(!request.getMethod().equals("OPTIONS")) {
            String accessToken = request.getHeader(AUTHORIZATION_HEADER).substring(TOKEN_PREFIX.length());
            UserDetails userDetails = JwtUtil.getPayload(accessToken);
            UserContext.setUserDetails(userDetails);
        }
        chain.doFilter(servletRequest, servletResponse);
    }
```

안되어야 하는 상황에서 되었던 이유는 브라우저나 Spring에서 성공했던 요청에 대해 캐싱을 해놓은 것으로 추정
Microsoft Edge 브라우저를 열고 닫으며 새 환경에서 테스트
