### ISSUE TITLE
[BE / 인증] redis client 오류

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#35]
### 문제
redis에 set 요청 시 클라이언트가 꺼져버림

redis client 생성 및 연결
![스크린샷 2022-01-27 오후 12 01 58](https://user-images.githubusercontent.com/24283401/151284474-e6f3403d-6463-43a0-94be-70177edc87ee.png)
![스크린샷 2022-01-27 오후 12 02 11](https://user-images.githubusercontent.com/24283401/151284504-ee5e99e6-448c-4442-997f-06e227638ba7.png)

set 요청을 하면 아래 사진과 같이 오류 발생
![스크린샷 2022-01-27 오후 12 02 33](https://user-images.githubusercontent.com/24283401/151284540-5cd010f5-e0bb-4e06-9279-127903d80b31.png)
![스크린샷 2022-01-27 오후 12 02 52](https://user-images.githubusercontent.com/24283401/151284579-526329dd-eda6-4536-9ef5-d3fff615bfa6.png)
로그를 찍어봤을 땐 redisClient 생성엔 문제 없는 것 같습니다..

**Comment by abc7468** [comment]
해당 redis가 켜져있는 환경에 redis-cli 에서 set 명령을 진행해 보시는게 어떨까요? --> 이 과정에서 안된다면 레디스 문제
docker로 올렸다면 각자 독립된 환경이라 코드상의 문제일듯 하옵니다. 또는 레디스 버전이 호환이 안되는 버전이거나??

**Comment by minjyo** [comment]
아 지금 로컬 환경입니다! 포스트맨으로 API 테스트하다가 발생한 오류인데 레디스를 처음 써봐서 해결방법을 잘 모르겠어서 이슈로 남겼습니다. redis-cli로 해보겠습니다!!

**Comment by minjyo** [comment]
오잉 여기선 잘 되는데 왜 노드에선 안될까요,,,?
![스크린샷 2022-01-27 오후 2 34 17](https://user-images.githubusercontent.com/24283401/151297981-e3e7b4a9-d466-4f3a-9b4a-e5df340da9ef.png)

**Comment by minjyo** [comment]
client connect를 await을 안하니까 되네요... 공식 문서에는 await으로 나와있었는데 ㅠㅠ
![스크린샷 2022-01-27 오후 3 01 09](https://user-images.githubusercontent.com/24283401/151300796-a6f3dc01-cb29-4269-bff9-0b47e7a5fe5d.png)

**Comment by minjyo** [comment]
+) get 오류 해결 완료
client.get() 은 promise를 반환하므로 await를 이용해 그 결과값을 얻을 수 있다. 두번째 방식대로 구현 하면 resolve 하지 않는이상 빠져나가지 않고 그 안에 멈춰있다.
![스크린샷 2022-01-27 오후 4 11 30](https://user-images.githubusercontent.com/24283401/151309183-8f50edf4-0eb4-4295-b52f-2d6cc2d299a5.png)

**Comment by Tae-Hyeon** [comment]
### redis 모듈 코드
![image](https://user-images.githubusercontent.com/20275668/152722914-d0c322b6-895d-403b-85b4-55b494d17bcb.png)

### uri 형식
- protocol: redis
- host: ip or DNS
- port: 6379
- ![image](https://user-images.githubusercontent.com/20275668/152723274-bc3fb9f1-76d9-48ab-8ceb-70caba1c154a.png)
