### ISSUE TITLE
[BE/ mysql] mysql connection 에러

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#42]
java 빌드파일 실행해서 개발진행 중에 mysql connection 에러가 생깁니다. VPN 사용하고 있지 않은 상태이고, AWS 쪽에 등록되지 않은 본가 IP로 접속해서 생긴 문제라고 생각되어 IP주소도 함께 남깁니다. 61.80.61.95
혹시 다른 에러라면 처리 부탁드립니다.
@Tae-Hyeon @abc7468 

![image](https://user-images.githubusercontent.com/48500209/151660155-558377f6-5d38-40a3-a527-19212c79becd.png)

![image](https://user-images.githubusercontent.com/48500209/151660136-b13f4125-3150-4430-b0b2-0d8041820bd9.png)

![image](https://user-images.githubusercontent.com/48500209/151660147-2c429ecb-abc4-4600-b624-ab68bd6f2415.png)

**Comment by Tae-Hyeon** [comment]
Git 사용량 제한으로 인한 connection error
