### ISSUE TITLE
[FE/ state 관리] 찜 추가/삭제를 한 번에 해버리는 문제

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#50]
현재 찜 상태를 `setState`로 관리하는데, 따라서 like 상태가 요청으로 인해 바뀌면, 다시 한 번 더 요청을 넣어버리는 문제가 생깁니다(state가 바뀌면 재 랜더링하는 리액트의 특성때문이라고 추측중) 
요청이 2번 들어감
- `wishes` : 찜하기
- `숫자` : 해당 `game`을 찜 취소하기
![image](https://user-images.githubusercontent.com/48500209/152484860-048d64ad-1a6a-4c76-badf-297c45e557b5.png)

관련 commit: https://github.com/STOVE-Milk/steam-clone/pull/43/commits/b6cb4f50ab452bd08d48a7186d109fb1472f7ce2 

관련 파일: [`GameInfo.tsx`](https://github.com/STOVE-Milk/steam-clone/blob/b6cb4f50ab452bd08d48a7186d109fb1472f7ce2/src/frontend/components/organisms/GameInfo.tsx)

관련코드
![image](https://user-images.githubusercontent.com/48500209/152484356-5d107063-8140-4d3c-a540-34bac18efd32.png)
![image](https://user-images.githubusercontent.com/48500209/152484366-68ce7881-eb33-4036-bdb8-e14b314b56f6.png)

@minjyo 지호님 시간되시면 헬프미 플리즈,,,,

<img src="https://media1.giphy.com/media/U7bo3ZBR8lcKSmGdlT/giphy.gif"/>

**Comment by minjyo** [comment]
### 방법 1.
제 추측으로는 wishFunc가 독립적이지 않고 setLike와 같이 onClick으로 묶여있어서, 클릭하지 않아도 호출이 되는 것 같습니다.

const unwish = () => {
       dispatch(
          doUnWish.request({
            game_id,
          }),
        );
      setLike(false);
}

const wish = () => {
       dispatch(
          doUnWish.request({
            game_id,
          }),
        )
      setLike(true);
}

<IconBox onClick={like ? () => unwish() : () => wish()}></IconBox>

이런식으로 wishFucn를 두개로 나누어서 setLike를 그 내부에 작성하여, onClilck함수를 하나만 할당해보는 방법은 어떠신가요

### 방법 2.
React.memo로 IconBox 감싸기
https://react.vlpt.us/basic/19-React.memo.html

**Comment by ummaeha** [comment]
결과: 동일하게 요청 2번 발생🥶
방법1
![image](https://user-images.githubusercontent.com/48500209/152517752-c7154504-c421-4ab1-ab9d-6cdfd4ba8dd3.png)


방법2
![image](https://user-images.githubusercontent.com/48500209/152515529-f444d548-8995-4244-bbc6-1190d7ce81ed.png)

@minjyo

**Comment by ummaeha** [comment]
해결했습니다. 


![image](https://user-images.githubusercontent.com/48500209/152527609-9a3f95cd-6399-41aa-8636-4f746febbba5.png)
제가 몽총이였어요.... 역시 디버깅은 콘솔 디버깅입니다... 콘솔찍어보니까 click에 따라서 요청은 한번씩만 되길래 redux탭을 봤더니 액션이 dowish로만 가서 이게 뭐지 하고봤더니 action명을 제가 잘못해놨네요..... ctrl cv의 폐해.....같이 고민해주셔서 감사합니다 이슈닫겠습니다
#43 


알려주신 React.memo는 회원가입 onchange에 도입해봐도 좋을 것 같아요. 렌더링이 너무 많이 일어나서 고민이었는데  예제랑 비슷하기두해서요!!
