### ISSUE TITLE
[BE/인증서버] 서버켜면 sequelize쪽에서 connection error, response안오고 pending만 지속되는 문제

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#52]
지난번에 같이 있을떄 했던 것처럼 로컬에서 `redis-server` `redis-cli `커멘드로 레디스 실행했고, `nodemon app.js` 했을 때 나타나는 오류입니다.

![image](https://user-images.githubusercontent.com/48500209/152671516-f9d34ca6-6e91-49fa-9ee3-7af6787b16d6.png)

이 사진에서보면 제가 입력한 이메일 `raya000@naver.com` 로 요청은 들어간듯 보입니다.
![image](https://user-images.githubusercontent.com/48500209/152671537-23a30e3b-26c0-4213-a1fd-6d02a414cac1.png)

![image](https://user-images.githubusercontent.com/48500209/152671520-6036b307-a623-4eb7-bc22-80afdcf03a1a.png)

**Comment by minjyo** [comment]
이건 MySQL 연결이 안되어서 생기는 문제인데, 성현님도 지금 연결이 안된다고 하네요..

**Comment by ummaeha** [comment]
AWS에 올려둔 mySQL이 다운된건가요?

**Comment by ummaeha** [comment]
1. VPN 꺼져있는지 확인하기
2. 기 등록된 IP가 맞는지 확인하기
