### ISSUE TITLE
[BE/멤버십] response의 guest_book에 updated_at 속성 추가

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#65]
**TODO**
방명록 조회 API /membership/profile/{userId}/guest-book 에서 
response의 guest_book에 updated_at 속성 추가부탁드립니다! 

**이유**
방명록이 수정됐을 때, (수정됨) 표시 추가 필요 

- 수정하시고 팀즈에 멘션 남겨주세요~

**Comment by Tae-Hyeon** [comment]
2022-02-13 16:00 수정 완료

멘션은 주말이라 안 남기겠습니다
