### ISSUE TITLE
[BE/멤버십] API 문서와 실제 통신에서의 response 형식 통일

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#67]
**방명록 조회**
API: /membership/profile/{userId}/guest-book
문서: guest_book: [{ ... }, ]
실제 응답: guest_books: [{ ... }, ]

**유저 검색**
API: /membership/search/users?nickname=nickname
문서: users: [{ ... }, ]
실제 응답: [{ ... }, ]

문서를 **response에 맞춰주세요!**

**Comment by minjyo** [comment]
+)
방명록 API header에 전부 authorization이 빠져있는데 들어가는게 맞죠?

**Comment by Tae-Hyeon** [comment]
GET 요청의 경우 필요가 없도록 만들려다 보니 실수한 것 같습니다.
프로필도 GET의 경우 authorization이 필요 없도록 만들려고 하고 있습니다.
쓰기, 삭제, 수정은 authorization이 필요한 게 맞습니다.

**Comment by Tae-Hyeon** [comment]
2022-02-13 16:27 수정 완료
guest_books -> guset_book
[] -> users: []
