### ISSUE TITLE
[BE/ gateway]  인가(Authorization) 안됨 / 메시지: 잘못된 JWT 서명입니다 

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#68]
#### 계정 정보

- 토큰 복호화는 잘 되는 것을 보니 jwt 토큰 자체에는 문제가 없다고 생각됩니다.
```
country: "KR"
exp: 1644563199
iat: 1644559599
idx: 52
nickname: "yasmin"
role: 1
```

- 10분전쯤 만든 계정이라서, expired 는 않았을 것 같고, 일단 게이트웨이쪽 로그에는 이렇게 뜹니다.
![image](https://user-images.githubusercontent.com/48500209/153545036-df747292-db72-4722-958f-9d91164e4192.png)

<img width="846" alt="image" src="https://user-images.githubusercontent.com/48500209/153545079-6786cc7a-2ca3-4a91-9110-795d31249a00.png">

확인 부탁드립니다 @Tae-Hyeon

**Comment by Tae-Hyeon** [comment]
JWT 서명이 잘못됐다는 것은 JWT Secret 키가 다르다는 것인데 지호님이 예전에 주신걸로 했어서 바뀌었는지 확인해야합니다.

**Comment by ummaeha** [comment]
@Tae-Hyeon  @minjyo 팀즈에서 말씀하신대로 시크릿키가 바뀐 것이 아니라면 다른 원인을 찾아봐야할 것 같습니다.

**Comment by minjyo** [comment]
시크릿키는 수정사항 없습니다.
JWT_SECRET=5dc5085d01e85fd229e32fedbd0f1a4b10cd57e61a7f423bca91263d7ce22ac5cf298a1f8ecc5f5f8125b07627329d06cbde50d25b5d00a17286cf577fd86e8b

**Comment by minjyo** [comment]
토큰 발급 및 검증

![스크린샷 2022-02-11 오후 3 56 35](https://user-images.githubusercontent.com/24283401/153549017-583387dc-0edc-4d58-9395-4ee06ee9beda.png)
![스크린샷 2022-02-11 오후 3 57 20](https://user-images.githubusercontent.com/24283401/153549130-8cd338b7-f278-46ab-8ca6-07aa286218fd.png)

**Comment by ummaeha** [comment]
프론트쪽에서 생성된 `token`만 인가과정에서 에러가 발생하는 것으로 확인

**Comment by Tae-Hyeon** [comment]
프론트 쪽에서 생성되었다는 것은 어떤 것인가요?? 토큰을 프론트쪽에서 수정이나 생성이 이루어지나요?

**Comment by ummaeha** [comment]
@minjyo  지호님 git으로 인증 서버 파일 주실때 env 환경변수 파일을 함께 안주셔서 걸리는거였네요.

해결해서 이슈 닫습니다
