### ISSUE TITLE
[BE/멤버십] 친구 검색 시, users에 친구 신청을 보낸 상태 추가하기

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#69]
유저 검색 API(/membership/search/users?nickname=nickname)에서 
그 유저에게 사용자(나)가 친구 신청을 보냈는지/안보냈는지 알 수 있도록 response에 추가해주실 수 있나요?

유저 검색한 화면에서, 다음과 같은 3가지로 유저를 표현하려고 합니다.

1. 플러스: 친구 신청을 보낼 수 있는 유저
<img width="1358" alt="스크린샷 2022-02-11 오후 5 12 28" src="https://user-images.githubusercontent.com/24283401/153557421-aeba3416-0a8a-45f2-9099-15e1172aae4f.png">

2. 체크: 친구 신청을 보낸 유저 (친구 수락 대기중인 유저)
(요청 사항)

3. 사람: 이미 친구인 유저
<img width="1349" alt="스크린샷 2022-02-11 오후 5 13 46" src="https://user-images.githubusercontent.com/24283401/153557556-05c7845c-1619-44de-b159-19fc62497f7c.png">

**Comment by Tae-Hyeon** [comment]
조금 오래 걸릴 것 같습니다.
Spring에서 JPA를 가지고 Join 쿼리를 한번에 처리하려는데 어렵네요.

**Comment by Tae-Hyeon** [comment]
결과가 이상하게 나와서 
제가 잘못 알고 사용한 줄 알았는데, 
알고 보니 토큰이 다른 id 라서 결과가 안 나온 거였네요.

wasRequested 라는 이름으로 적용했습니다.
