### ISSUE TITLE
[BE/ 인증서버] 회원가입 시도시 로그만 찍히고 에러가 response로 오지 않음. 

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#84]
회원가입 시도시 로그만 찍히고 에러가 response로 오지 않음. ( http://localhost:8101/auth/signup )

백엔드 코드를 봐보니 `auth.js` 파일에  에러상황에 `console.log` 처리만 되어있음
<img width="483" alt="image" src="https://user-images.githubusercontent.com/48500209/153854759-a7e02226-6089-42b2-85e4-da3701b09136.png">

https://user-images.githubusercontent.com/48500209/153854777-ab608ca8-d44b-4c81-87bc-780607a4172e.mov

Postman 시도화면
![Screen Shot 2022-02-14 at 8 17 08 PM](https://user-images.githubusercontent.com/48500209/153855141-1a1b5cc9-7f1b-4e7f-804b-5ebbaced03f2.png)

문제점
- 프론트에서 에러처리를 할 수 없음

**Comment by minjyo** [comment]
우선 순위에 밀려서 나중에 시간이 된다면 처리하겠습니다.
프론트에서 닉네임 중복 체크에 대한 응답 처리를 해주시면 애초에 회원가입 진행이 되지 않으니 해결되겠습니다. 
@ummaeha
