### ISSUE TITLE
[BE/채팅] 웹소켓 통신 오류 및 프로토콜

### ISSUE THREAD

**Issue by minjyo** [STOVE-Milk/steam-clone#90]
1. room-get: 개인 채팅방은 불러오지만, 단체 채팅방을 불러오지 못함

2. room-view: 서버가 멈춤
![스크린샷 2022-02-15 오후 5 43 21](https://user-images.githubusercontent.com/24283401/154049968-247c76ae-58a6-425d-a458-01fab52233c6.png)

3. 프로토콜 업데이트 - https://proud-myself-yasmine.notion.site/JSON-ce3100cf3bd34798b4a48c3646c2fb16

**Comment by abc7468** [comment]
1, 2 문제가 동일한 원인으로 생긴 문제였습니다.
현재 room을 다루는 객체는 DB 데이터를 다루는 객체와 웹 소캣 서버가 가지는 객체 두가지가 있습니다.
그 상황에서 방의 DB정보를 통해 웹 소캣 서버에 저장된 객체를 찾는 단계에 변수를 착각하여 다시 DB 데이터를 리턴 하였습니다.
이 부분을 수정하여 문제를 해결하였습니다.

3.  leave-room 액션에 대한 처리를 수정해 놓았습니다.
